#!/bin/bash
# ==============================================================================
# ⚠️ WARNING: This script was generated by AI. Unexpected issues or behaviors
# may occur during its execution. Always verify your files and repository state.
# — vSKAH
# ==============================================================================
set -e

# Move to project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

# Terminal colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Display warning
echo -e "${YELLOW}┌────────────────────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│ ⚠️  WARNING: This script was generated by AI. Unexpected issues may   │${NC}"
echo -e "${YELLOW}│     occur. Always verify your repository state after execution.        │${NC}"
echo -e "${YELLOW}│     — vSKAH                                                            │${NC}"
echo -e "${YELLOW}└────────────────────────────────────────────────────────────────────────┘${NC}"
echo ""

# SemVer 2.0.0 regex (supports suffixes like -SNAPSHOT, -rc.1, etc.)
SEMVER_REGEX="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$"

# 1. Retrieve current version
CURRENT_VERSION=$(grep -m 1 "<version>" pom.xml | sed -E 's/.*<version>(.*)<\/version>.*/\1/' | tr -d ' ')

echo -e "${BLUE}=== 🚀 Tachyon Version Bump ===${NC}"
echo -e "Current version: ${YELLOW}${CURRENT_VERSION}${NC}"
echo ""

# 2. Prompt loop with SemVer validation
while true; do
    read -r -p "Enter new version (e.g. 2.1.0 or 2.1.0-SNAPSHOT): " NEW_VERSION

    # Check if empty
    if [ -z "$NEW_VERSION" ]; then
        echo -e "${RED}❌ Version cannot be empty. Please try again (or Ctrl+C to abort).${NC}"
        continue
    fi

    # Validate SemVer
    if [[ "$NEW_VERSION" =~ $SEMVER_REGEX ]]; then
        break
    else
        echo -e "${RED}❌ '$NEW_VERSION' does not follow SemVer format (X.Y.Z[-PRERELEASE]).${NC}"
        echo -e "${CYAN}💡 Valid examples: 2.1.0, 2.1.0-SNAPSHOT, 2.0.0-rc.1, 1.0.1-beta.2${NC}"
        echo ""
    fi
done

echo ""
echo -e "${BLUE}⏳ Applying version ${NEW_VERSION}...${NC}"

# 3. Update all pom.xml files via Maven
mvn versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false

# 4. Update (or create) IntelliJ template
TEMPLATE_FILE=".idea/fileTemplates/includes/File Header.java"
if [ -f "$TEMPLATE_FILE" ]; then
    sed -i '' "s/#set( \$MAVEN_VERSION = .*/#set( \$MAVEN_VERSION = \"$NEW_VERSION\" )/" "$TEMPLATE_FILE"
    echo -e "${GREEN}✓ IntelliJ template updated: ${TEMPLATE_FILE}${NC}"
else
    mkdir -p ".idea/fileTemplates/includes"
    cat <<EOF > "$TEMPLATE_FILE"
#set( \$MAVEN_VERSION = "$NEW_VERSION" )
/**
 * Short class explanation
 * <p>
 * Long class explanation with @link if needed
 * </p>
 *
 * <p><i>Project \${PROJECT_NAME}</i></p>
 *
 * @author Jimmy (vSKAH) - \${DATE}
 * @version 1.0
 * @since \$MAVEN_VERSION
 */
EOF
    echo -e "${GREEN}✓ IntelliJ template created: ${TEMPLATE_FILE}${NC}"
fi

echo ""
echo -e "${GREEN}🎉 Success! Tachyon project updated to version ${NEW_VERSION} (SemVer validated).${NC}"
