<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>tech.sk-works.minecraft</groupId>
    <artifactId>tachyon-parent</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>tachyon-common</module>
        <module>tachyon-api</module>
        <module>tachyon-service</module>
        <module>tachyon-minecraft-plugin</module>
        <module>tachyon-minecraft-example</module>
    </modules>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <protobuf.version>4.33.2</protobuf.version>
        <grpc.version>1.79.0</grpc.version>
    </properties>

    <distributionManagement>
        <repository>
            <id>reposilite-releases</id>
            <url>https://reposilite.skworks.tech/releases</url>
        </repository>

        <snapshotRepository>
            <id>reposilite-snapshots</id>
            <url>https://reposilite.skworks.tech/snapshots</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.18.0</version>
                <configuration>
                    <generateBackupPoms>false</generateBackupPoms>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
