name: Tachyon-Cookies
version: 1.0
main: tech.skworks.tachyon.exempleplugin.TachyonCookies
depend: [Tachyon-Core]
commands:
  cookie:
    description: Jouer au Cookie Clicker quantique
    aliases: [cookies]
