name: Tachyon-Core
description: Bridge between tachyon service and bukkit server
version: 1.0.0-SNAPSHOT
author: "vSKAH"
main: tech.skworks.tachyon.plugin.spigot.TachyonCore
softdepend:
  - "spark"
commands:
  snapshot:
    description: "Manage tachyon snapshot"
    aliases: ["snapshots"]
