quarkus.container-image.build=false
quarkus.container-image.push=false
quarkus.container-image.registry=docker-registry.skworks.tech
quarkus.container-image.group=skworks
quarkus.container-image.name=tachyon-service
quarkus.container-image.tag=1.0.0-SNAPSHOT
quarkus.container-image.insecure=true
quarkus.container-image.builder=jib
quarkus.jib.platforms=linux/amd64

quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{trace_id}, parentId=%X{parent_id}, spanId=%X{span_id}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

quarkus.grpc.server.max-inbound-message-size=33554432
quarkus.grpc.server.netty.permit-keep-alive-without-calls=true
quarkus.grpc.server.netty.permit-keep-alive-time=PT10S

quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

quarkus.mongodb.database=tachyon
quarkus.mongodb.max-pool-size=200
quarkus.mongodb.min-pool-size=20
quarkus.mongodb.max-connection-idle-time=PT60S
quarkus.mongodb.server-selection-timeout=PT5S
quarkus.mongodb.connect-timeout=PT5S
quarkus.mongodb.read-timeout=PT10S
quarkus.mongodb.write-concern.w=majority
quarkus.mongodb.write-concern.journal=true
quarkus.mongodb.read-preference=primaryPreferred