quarkus.container-image.build=true
quarkus.container-image.push=true
quarkus.container-image.registry=docker-registry.skworks.tech
quarkus.container-image.group=skworks
quarkus.container-image.name=tachyon-service
quarkus.container-image.tag=1.0.0-SNAPSHOT
quarkus.container-image.insecure=true
quarkus.container-image.builder=jib
quarkus.jib.platforms=linux/amd64

quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{trace_id}, parentId=%X{parent_id}, spanId=%X{span_id}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

quarkus.grpc.server.max-inbound-message-size=33554432
quarkus.grpc.server.netty.permit-keep-alive-without-calls=true
quarkus.grpc.server.netty.permit-keep-alive-time=PT10S

quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

tachyon.database.name=tachyon

tachyon.player.stream-key=tachyon:mongo_stream
tachyon.player.collection=players
tachyon.player.snapshots-collection=player_snapshots

tachyon.audit.stream-key=tachyon:audit_stream
tachyon.audit.collection=audit_logs

tachyon.snapshot.players-collection=players
tachyon.snapshot.snapshots-collection=player_snapshots
tachyon.snapshot.s3-bucket=tachyon
tachyon.snapshot.retention-days=7
tachyon.snapshot.max-concurrent-uploads=10
tachyon.snapshot.throttle-seconds=300
